{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix # Generated by nixos-generate-config
  ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "magic"; # Your machine name
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "America/New_York";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  # Define a user account.
  users.users.jr = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "networkmanager"
    ];
    shell = pkgs.nushell;
    packages = with pkgs; [
      # Minimal system-level apps; keep the rest in Home Manager
      git
      vim
      curl
      wget
    ];
  };

  # Essential system services
  services.openssh.enable = true;
  services.printing.enable = false; # Keep it minimal

  # List packages installed in system profile.
  environment.systemPackages = with pkgs; [
    jujutsu # System-wide jj access
    helix # Your editor of choice
  ];

  # Enable Flakes and the 'nix' command
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # Allow unfree packages (like some drivers or firmware)
  nixpkgs.config.allowUnfree = true;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  system.stateVersion = "25.11";
}
